-- ============================================================
-- Magnitude Analysis
-- Analyze the scale and distribution of customers, products,
-- costs, revenue, and sales volume across key dimensions
-- ============================================================



-- Analyze Customer Magnitude by Country
-- Determine the number of customers in each country
SELECT 
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Analyze Customer Magnitude by Gender
-- Determine the number of customers within each gender group
SELECT 
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Analyze Product Magnitude by Category
-- Determine the number of products available in each category
SELECT 
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Analyze Average Product Cost by Category
-- Compare the average product cost across different categories
SELECT 
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- Analyze Revenue Magnitude by Category
-- Determine the total revenue generated by each product category
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Analyze Revenue Magnitude by Customer
-- Identify the total revenue generated by each customer
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    c.gender,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name,
    c.gender
ORDER BY total_revenue DESC;


-- Analyze Sales Volume by Country
-- Determine the total number of items sold across each country
SELECT 
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

